.catalog:
  name: "PgAdmin "
  description: "This is PgAdmin all set up and ready to go in Rancher."
  version: 1
  uuid: geoilocate-pgadmin
  questions:
  - variable: PGADMIN_EMAIL
    description: "Email address to login into the database"
    label: "Login Email address"
    required: true
    default: "pgadmin@docker.com"
    type: "string"
  - variable: PGADMIN_PASSWORD
    description: "Password to login to pgadmin"
    label: "Password to login to pgadmin"
    required: true
    default: "pgadmin4"
    type: "password"
  - variable: PGADMIN_VERSION
    label: "PGADMIN  version"
    description: "PGADMIN version"
    required: true
    default: "4.16"
    type: "string"
  - variable: "HOST_AFFINITY"
    label: "Label of host to deploy on"
    description: |
      To keep containers running on specific
      hosts, provide label attached to host
      to deploy on. For example, if you create a label 
      when deploying your host with key gis-box-id
      and value 3 then you would enter here gis-box-id=3
    required: true
    type: string
    default:
