rabbit:
  image: kobotoolbox/rabbit:latest
  # Dev: Build the image locally.
  # build: ./base_images/rabbit
  hostname: rabbit
  environment:
    - RABBITMQ_LOG_BASE=/var/log/rabbitmq
  volumes:
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/log/rabbitmq:/var/log/rabbitmq
  restart: on-failure

postgres:
  #image: kobotoolbox/postgres:latest
  image: mdillon/postgis:9.5
  # Dev: Build the image locally.
  # build: ./base_images/postgres
  hostname: postgres
  #env_file:
  #  - ./envfile.local.txt

  environment:
    - HOST_ADDRESS=172.17.0.1
    - ENKETO_API_TOKEN=OvjbAh6YUK4ruQ2royzm62QfENI4LXF1t0EF5VjBxcwnjKkWL5
    - DJANGO_SECRET_KEY=w-j8!wfn+s#twrc!y5sl9s2j4f6^fn^6wps(lc_566%&^3b!ys
    - KOBO_SUPERUSER_USERNAME=admin
    - KOBO_SUPERUSER_PASSWORD=dl@l1nux
    - KOBO_SUPPORT_EMAIL=info@geoilocate.co.za
    - KPI_PUBLIC_PORT=7000
    - KOBOCAT_PUBLIC_PORT=7001
    - ENKETO_EXPRESS_PUBLIC_PORT=7005

  #env_file:
  #  - ./envfile.local.txt

  environment:
    - HOST_ADDRESS=172.17.0.1
    - ENKETO_API_TOKEN=OvjbAh6YUK4ruQ2royzm62QfENI4LXF1t0EF5VjBxcwnjKkWL5
    - DJANGO_SECRET_KEY=w-j8!wfn+s#twrc!y5sl9s2j4f6^fn^6wps(lc_566%&^3b!ys
    - KOBO_SUPERUSER_USERNAME=admin
    - KOBO_SUPERUSER_PASSWORD=dl@l1nux
    - KOBO_SUPPORT_EMAIL=info@geoilocate.co.za
    - KPI_PUBLIC_PORT=7000
    - KOBOCAT_PUBLIC_PORT=7001
    - ENKETO_EXPRESS_PUBLIC_PORT=7005

    - POSTGRES_PORT=5432
    - POSTGRES_HOST=postgres
    - POSTGRES_DB=kobotoolbox
    - POSTGRES_USER=kobo
    - POSTGRES_PASSWORD=kobo

    - DATABASE_URL=postgis://kobo:kobo@postgres:5432/kobotoolbox




  volumes:
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/.vols/db:/srv/db
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/backups/postgres:/srv/backups
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/base_images/postgres/init_postgres.bash:/etc/my_init.d/10_init_postgres.bash:ro
  restart: on-failure

mongo:
  image: kobotoolbox/mongo:latest
  # Dev: Build the image locally.
  # build: ./base_images/mongo
  hostname: mongo
  environment:
    - MONGO_DATA=/srv/db
  #env_file:
  #  - ./envfile.local.txt
    - HOST_ADDRESS=172.17.0.1
    - ENKETO_API_TOKEN=OvjbAh6YUK4ruQ2royzm62QfENI4LXF1t0EF5VjBxcwnjKkWL5
    - DJANGO_SECRET_KEY=w-j8!wfn+s#twrc!y5sl9s2j4f6^fn^6wps(lc_566%&^3b!ys
    - KOBO_SUPERUSER_USERNAME=admin
    - KOBO_SUPERUSER_PASSWORD=dl@l1nux
    - KOBO_SUPPORT_EMAIL=info@geoilocate.co.za
    - KPI_PUBLIC_PORT=7000
    - KOBOCAT_PUBLIC_PORT=7001
    - ENKETO_EXPRESS_PUBLIC_PORT=7005


    - POSTGRES_PORT=5432
    - POSTGRES_HOST=postgres
    - POSTGRES_DB=kobotoolbox
    - POSTGRES_USER=kobo
    - POSTGRES_PASSWORD=kobo

    - DATABASE_URL=postgis://kobo:kobo@postgres:5432/kobotoolbox






  # NOTE: On OS X and Windows, comment out the following `volumes` directive
  #   as a workaround to a VirtualBox folder sharing+Mongo incompatibility.
  #   See the "WARNING" at https://hub.docker.com/_/mongo/
  volumes:
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/.vols/mongo:/srv/db
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/backups/mongo:/srv/backups
  restart: on-failure

kobocat:
  #image: kobotoolbox/kobocat:latest
  image: kobotoolbox/kobocat:latest
  # Dev: Build the image locally.
  # build: ../kobocat
  hostname: kobocat
  #env_file:
    #- ./envfile.local.txt
    #- ./aws.txt
    #- ./external_services.txt
    #- ./kobocat.txt
    #- ./nginx.txt
    #- ./smtp.txt
  links:
    - rabbit
    - mongo
    - postgres
    - kpi
  volumes:
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/.vols/static/kobocat:/srv/static
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/.vols/kobocat_media_uploads:/srv/src/kobocat/media
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/backups/kobocat:/srv/backups
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/log/kobocat:/srv/logs
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/scripts/wait_for_rabbit.bash:/etc/my_init.d/01_wait_for_rabbit.bash:ro
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/scripts/wait_for_mongo.bash:/etc/my_init.d/02_wait_for_mongo.bash:ro
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/scripts/wait_for_postgres.bash:/etc/my_init.d/03_wait_for_postgres.bash:ro
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/scripts/wait_for_kpi.bash:/etc/my_init.d/04_wait_for_kpi.bash:ro
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/scripts/runtime_variables_kobocat.source.bash:/etc/profile.d/runtime_variables_kobocat.source.bash.sh:ro
    # Dev: Use live source directories from the host machine.
    # - ../kobocat:/srv/src/kobocat
    #- ../formpack/src/formpack:/usr/local/lib/python2.7/dist-packages/formpack
    # Dev: Share PyDev remote debugger source into container.
    #- ~/devel/liclipse/plugins/org.python.pydev_5.4.0.201611281405/pysrc:/srv/pydev_orig:ro
    # Dev: Share your `.transifexrc` into the container.
    # - ./.transifexrc:/root/.transifexrc
  environment:
    - ENKETO_PROTOCOL=http
    #  - ./envfile.local.txt
    - HOST_ADDRESS=172.17.0.1
    - ENKETO_API_TOKEN=OvjbAh6YUK4ruQ2royzm62QfENI4LXF1t0EF5VjBxcwnjKkWL5
    - DJANGO_SECRET_KEY=w-j8!wfn+s#twrc!y5sl9s2j4f6^fn^6wps(lc_566%&^3b!ys
    - KOBO_SUPERUSER_USERNAME=admin
    - KOBO_SUPERUSER_PASSWORD=dl@l1nux
    - KOBO_SUPPORT_EMAIL=info@geoilocate.co.za
    - KPI_PUBLIC_PORT=7000
    - KOBOCAT_PUBLIC_PORT=7001
    - ENKETO_EXPRESS_PUBLIC_PORT=7005
    #- ./aws.txt

    #- ./external_services.txt

    #- ./kobocat.txt
    - KOBOCAT_DJANGO_DEBUG=False
    - TEMPLATE_DEBUG=False

    - DJANGO_SETTINGS_MODULE=onadata.settings.kc_environ
    - ENKETO_VERSION=Express
    - DATABASE_URL=postgis://kobo:kobo@postgres:5432/kobotoolbox
    - KOBO_POSTGRES_DB_NAME=kobotoolbox
    - KOBO_POSTGRES_USER=kobo
    - KOBO_POSTGRES_PASSWORD=kobo
    - KOBOCAT_BROKER_URL=amqp://kobocat:kobocat@rabbit:5672/kobocat

    #- ./nginx.txt
    - KPI_WEB_SERVER=uWSGI
    - KOBOCAT_WEB_SERVER=uWSGI
    - KOBOCAT_STATIC_FILES_SERVER=Nginx
    - KPI_STATIC_FILES_SERVER=Nginx

    #- ./smtp.txt
  restart: on-failure


kpi:
  #image: kobotoolbox/kpi:latest
  image: kobotoolbox/kpi:latest
  # Dev: Build the image locally.
  # build: ../kpi
  hostname: kpi
  #env_file:
  environment:
    #  - ./envfile.local.txt
    - HOST_ADDRESS=172.17.0.1
    - ENKETO_API_TOKEN=OvjbAh6YUK4ruQ2royzm62QfENI4LXF1t0EF5VjBxcwnjKkWL5
    - DJANGO_SECRET_KEY=w-j8!wfn+s#twrc!y5sl9s2j4f6^fn^6wps(lc_566%&^3b!ys
    - KOBO_SUPERUSER_USERNAME=admin
    - KOBO_SUPERUSER_PASSWORD=dl@l1nux
    - KOBO_SUPPORT_EMAIL=info@geoilocate.co.za
    - KPI_PUBLIC_PORT=7000
    - KOBOCAT_PUBLIC_PORT=7001
    - ENKETO_EXPRESS_PUBLIC_PORT=7005

    #- ./aws.txt
    #- ./external_services.txt
    #- ./kpi.txt
    - KPI_DJANGO_DEBUG=False
    - TEMPLATE_DEBUG=False

    - ENKETO_VERSION=Express
    - KPI_PREFIX=/
    - KPI_BROKER_URL=amqp://kpi:kpi@rabbit:5672/kpi
    - DATABASE_URL=postgres://kobo:kobo@postgres:5432/kobotoolbox
    - KOBO_POSTGRES_DB_NAME=kobotoolbox
    - KOBO_POSTGRES_USER=kobo
    - KOBO_POSTGRES_PASSWORD=kobo

    #- ./nginx.txt
    - KPI_WEB_SERVER=uWSGI
    - KOBOCAT_WEB_SERVER=uWSGI
    - KOBOCAT_STATIC_FILES_SERVER=Nginx
    - KPI_STATIC_FILES_SERVER=Nginx

    #- ./smtp.txt
  links:
    - postgres
    - rabbit
    - mongo
  volumes:
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/.vols/static/kpi:/srv/static
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/.vols/kpi_media:/srv/src/kpi/media
    # The Whoosh search index needs persistent storage
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/.vols/whoosh:/srv/whoosh
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/log/kpi:/srv/logs
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/scripts/wait_for_rabbit.bash:/etc/my_init.d/01_wait_for_rabbit.bash:ro
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/scripts/wait_for_mongo.bash:/etc/my_init.d/02_wait_for_mongo.bash:ro
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/scripts/wait_for_postgres.bash:/etc/my_init.d/03_wait_for_postgres.bash:ro
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/scripts/create_kobo_superuser.bash://etc/my_init.d/20_create_kobo_superuser.bash:ro
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/scripts/runtime_variables_kpi.source.bash:/etc/profile.d/runtime_variables_kpi.source.bash.sh:ro
    # Dev: Use live source directories from the host machine.
    # - ../kpi:/srv/src/kpi
    #- ../formpack/src/formpack:/usr/local/lib/python2.7/dist-packages/formpack
    # Allow access to Kobocat's media uploads within KPI
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/.vols/kobocat_media_uploads:/srv/src/kobocat/media
    # Dev: Share PyDev remote debugger source into container.
    #- ~/devel/liclipse/plugins/org.python.pydev_5.4.0.201611281405/pysrc:/srv/pydev_orig:ro
    # Dev: Share your `.transifexrc` into the container.
    # - ./.transifexrc:/root/.transifexrc
  restart: on-failure

nginx:
  image: kobotoolbox/nginx:latest
  # Dev: Build the image locally.
  # build: ./base_images/nginx
  hostname: nginx
  #env_file:
    #- ./envfile.local.txt
    #- ./nginx.txt
    #- ./kobocat.txt
    #- ./kpi.txt
  environment:
    #  - ./envfile.local.txt
    - HOST_ADDRESS=172.17.0.1
    - ENKETO_API_TOKEN=OvjbAh6YUK4ruQ2royzm62QfENI4LXF1t0EF5VjBxcwnjKkWL5
    - DJANGO_SECRET_KEY=w-j8!wfn+s#twrc!y5sl9s2j4f6^fn^6wps(lc_566%&^3b!ys
    - KOBO_SUPERUSER_USERNAME=admin
    - KOBO_SUPERUSER_PASSWORD=dl@l1nux
    - KOBO_SUPPORT_EMAIL=info@geoilocate.co.za
    - KPI_PUBLIC_PORT=7000
    - KOBOCAT_PUBLIC_PORT=7001
    - ENKETO_EXPRESS_PUBLIC_PORT=7005

    #- ./nginx.txt
    - KPI_WEB_SERVER=uWSGI
    - KOBOCAT_WEB_SERVER=uWSGI
    - KOBOCAT_STATIC_FILES_SERVER=Nginx
    - KPI_STATIC_FILES_SERVER=Nginx

    #- ./kobocat.txt
    - KOBOCAT_DJANGO_DEBUG=False
    - TEMPLATE_DEBUG=False

    - DJANGO_SETTINGS_MODULE=onadata.settings.kc_environ
    - ENKETO_VERSION=Express
    - DATABASE_URL=postgis://kobo:kobo@postgres:5432/kobotoolbox
    - KOBO_POSTGRES_DB_NAME=kobotoolbox
    - KOBO_POSTGRES_USER=kobo
    - KOBOCAT_BROKER_URL=amqp://kobocat:kobocat@rabbit:5672/kobocat

    #- ./kpi.txt
    - KPI_DJANGO_DEBUG=False
    #- TEMPLATE_DEBUG=False

    #- ENKETO_VERSION=Express
    - KPI_PREFIX=/
    - KPI_BROKER_URL=amqp://kpi:kpi@rabbit:5672/kpi
    - DATABASE_URL=postgres://kobo:kobo@postgres:5432/kobotoolbox


    - NGINX_CONFIG_FILE_NAME=nginx_site_http.conf

  ports:
    # NOTE: The host ports (left of the ":") must match the values in
    #   `envfile.local.txt`. Do not modify the container ports (right side).
    - 7000:9000 # KPI
    - 7001:9001 # KoBoCAT
    - 7005:9005 # Enketo Express
  volumes:
      - /home/sindile/gitrepo/kobotoolbox/docker-kobo/.vols/static:/srv/www:ro
      # get the logs out of glusterfs!
      - /home/sindile/gitrepo/kobotoolbox/docker-kobo/log/nginx:/var/log/nginx
      - /home/sindile/gitrepo/kobotoolbox/docker-kobo/nginx/:/tmp/kobo_nginx/:ro
      - /home/sindile/gitrepo/kobotoolbox/docker-kobo/nginx/nginx_command.bash:/etc/service/nginx/run:ro
  links:
    - kobocat
    - kpi
    - enketoexpress
  restart: on-failure

# Adapted from https://github.com/kobotoolbox/enketo-express/blob/docker/docker-compose.yml.
enketoexpress:
  image: kobotoolbox/enketo-express-extra-widgets:1.55.6
  #image: kobotoolbox/enketo-express-extra-widgets:1.61.4
  # Dev: Build the image locally.
  # build: ../enketo-express/
  #env_file:
    #- ./envfile.local.txt
    #- ./external_services.txt
  environment:
    #  - ./envfile.local.txt
    - HOST_ADDRESS=172.17.0.1
    - ENKETO_API_TOKEN=OvjbAh6YUK4ruQ2royzm62QfENI4LXF1t0EF5VjBxcwnjKkWL5
    - DJANGO_SECRET_KEY=w-j8!wfn+s#twrc!y5sl9s2j4f6^fn^6wps(lc_566%&^3b!ys
    - KOBO_SUPERUSER_USERNAME=admin
    - KOBO_SUPERUSER_PASSWORD=dl@l1nux
    - KOBO_SUPPORT_EMAIL=info@geoilocate.co.za
    - KPI_PUBLIC_PORT=7000
    - KOBOCAT_PUBLIC_PORT=7001
    - ENKETO_EXPRESS_PUBLIC_PORT=7005
    #- ./external_services.txt

    - ENKETO_REDIS_MAIN_HOST=172.17.0.1
    - ENKETO_REDIS_CACHE_HOST=172.17.0.1
    - ENKETO_LINKED_FORM_AND_DATA_SERVER_SERVER_URL=172.17.0.1
    - ENKETO_SUPPORT_EMAIL=info@geoilocate.co.za




  links:
    - redismain
    - rediscache
  restart: on-failure
  volumes:
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/scripts/runtime_variables_enketo_express.source.bash:/etc/profile.d/runtime_variables_enketo_express.source.bash.sh:ro
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/enketo_express/config.json:/srv/tmp/enketo_express_config.json:ro
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/scripts/enketo_express_copy_config.bash:/etc/my_init.d/01_enketo_express_copy_config.bash:ro
    # Override Enketo Express icons.
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/enketo_express/favicon.ico:/srv/src/enketo_express/public/images/favicon.ico:ro
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/enketo_express/icon_180x180.png:/srv/src/enketo_express/public/images/icon_180x180.png:ro
    # Dev: Use the live `enketo-express` directory from the host machine.
    # - ../enketo-express:/srv/src/enketo_express

# Adapted from https://github.com/kobotoolbox/enketo-express/blob/docker/docker-compose.yml.
redismain:
  image: redis:2.6
  #image: redis:3.2
  # Map our "main" Redis config into the container.
  volumes:
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/redis/redis-enketo-main.conf:/etc/redis/redis.conf:ro
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/.vols/redis_main_data/:/data/
  restart: on-failure
  #ports:
  #  - 6379:6379
  #sysctls:
  #  - net.core.somaxconn=2048

# Adapted from https://github.com/kobotoolbox/enketo-express/blob/docker/docker-compose.yml.
rediscache:
  image: redis:2.6
  #image: redis:3.2
  # Map our "cache" Redis config into the container.
  volumes:
    - /home/sindile/gitrepo/kobotoolbox/docker-kobo/redis/redis-enketo-cache.conf:/etc/redis/redis.conf:ro
  restart: on-failure
  #ports:
  #  - 6379:6379
  #sysctls:
  #  - net.core.somaxconn=2048
